This is a testharness.js-based test.
FAIL Use NewTarget's prototype, not the one stored at definition time promise_test: Unhandled rejection with value: object "TypeError: Cannot read property 'appendChild' of null"
FAIL Rethrow any exceptions thrown while getting the prototype promise_test: Unhandled rejection with value: object "TypeError: Cannot read property 'appendChild' of null"
FAIL If prototype is not object, derives the fallback from NewTarget's realm (autonomous custom elements) promise_test: Unhandled rejection with value: object "TypeError: Cannot read property 'appendChild' of null"
FAIL If prototype is not object, derives the fallback from NewTarget's realm (customized built-in elements) promise_test: Unhandled rejection with value: object "TypeError: Cannot read property 'appendChild' of null"
Harness: the test ran to completion.

