This is a testharness.js-based test.
FAIL Verify XHR does not exist assert_unreached: unexpected rejection: Blocked a frame with origin "https://web-platform.test:8444" from accessing a cross-origin frame. Reached unreachable code
Harness: the test ran to completion.

